// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyApi.Models;
using System;

namespace MyApi.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20171023150419_EditEstablishmentsModel")]
    partial class EditEstablishmentsModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyApi.Models.Establishments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<int>("PostalCode")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("MyApi.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("EstablishmentID");

                    b.Property<string>("Password");

                    b.Property<string>("Skey");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyApi.Models.Users", b =>
                {
                    b.HasOne("MyApi.Models.Establishments", "Establishment")
                        .WithMany("Users")
                        .HasForeignKey("EstablishmentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
