// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyApi.Models;
using System;

namespace MyApi.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    partial class ApiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyApi.Models.Establishments", b =>
                {
                    b.Property<int>("EstablishmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("PostalCode")
                        .HasMaxLength(5);

                    b.HasKey("EstablishmentID");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("MyApi.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("EstablishmentID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Skey")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Username")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.HasIndex("EstablishmentID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyApi.Models.Users", b =>
                {
                    b.HasOne("MyApi.Models.Establishments", "Establishment")
                        .WithMany("Users")
                        .HasForeignKey("EstablishmentID")
                        .HasConstraintName("EstablishmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
